### PR TITLE
Fix for #29: implementing a solution for tabular data

### PR DESCRIPTION
**Pull request by chrisblock**
This implements a fix for #29 by creating an abstraction over HTML table elements.

### CODE REVIEW

**Comment by toddmeinershagen** [comment]
@chrisblock  - Thanks for this pull request.  Lots of interesting stuff around table manipulation.  Thanks for including so many tests to demonstrate the use of the abstraction. 

I am wondering if the Columns property of ITable interface should be Headers instead.  Thoughts?  

Also, I am wondering if we ought to call GetHeader<T> HeaderAs<T>, GetRows<T> RowsAs<T> and GetFooter FooterAs<T> so that the client will see both options side-by-side.  Example, .Headers, .HeaderAs<T>.  Thoughts?

**Comment by chrisblock** [comment]
@toddmeinershagen - I agree with your suggestions and have put in another commit containing those changes.

**Comment by toddmeinershagen** [comment]
@chrisblock - Thanks for issuing this request.  I think this functionality will definitely make it easier for users to deal with simple table structures in their application.  In the future, I think similar functionality to make repeating rows (without headers/footers) that are not dependent on a ```<table>``` element would be beneficial as well.  Using SpecificBlock is still not as intuitive.

I took a look at your changes and have a few questions.  

* Do we need to upgrade Selenium from 2.42 to 2.44?  If so, we need to update the .nuspec file to make that a minimum so that clients are upgraded.
* I like the browser environments that you created, although, I have already taken that idea and implemented the various browsers in the main package.  Would you remove your implementations and just use the built-in ones for this request?
* Please remove the RhinoMocks reference.  If you needs mocks, let's use NSubstitute.
* Does it make more sense to provide an ITable<TRows> so that people who develop pages can specify how a table should be interpreted instead of leaving that up to the tester writing the test scripts against those objects using the RowsAs<TRow>, HeadersAs<THeader>, FooterAs<TFooter>?  It might make it more reusable across tests.

**Comment by toddmeinershagen** [comment]
@chrisblock - I merge your changes and think this will be a good addition to the existing elements we support.  So, thank you...

I made the mods as mentioned above and fixed a test for threaded sessions that was failing.  Instead of calling the Wait() method on each task, it needed to call Task.WaitAll() and pass in the array of tasks that were started/run.

**Pull request merged**
